#!/bin/sh


echo ".timeout 10000" > /tmp/commands.sql
echo "INSERT INTO delivery_queue (delivery_cmd, cmd_arg_1, cmd_arg_2, cmd_arg_3) VALUES ('Calc Injector Mfac', $1, $2, $3);" >> /tmp/commands.sql
echo ".quit" >> /tmp/commands.sql
sqlite3 /dev/shm/accu4_db_ram.sqlite < /tmp/commands.sql
rm -rf /tmp/commands.sql
