#!/bin/sh

echo ".timeout 10000" > /tmp/commands.sql
echo ".headers ON" >> /tmp/commands.sql
echo "select recipe_config_id, recipe_used, recipe_name from recipe_config where recipe_used>0;" >> /tmp/commands.sql
echo ".quit" >> /tmp/commands.sql
sqlite3 /media/data/database/accu4_db.sqlite < /tmp/commands.sql
rm -rf /tmp/commands.sql
