#!/bin/sh

echo ".timeout 10000" > /tmp/commands.sql
echo "INSERT INTO delivery_queue (delivery_cmd, arm_no) VALUES ('End Batch', $1);" >> /tmp/commands.sql
echo ".quit" >> /tmp/commands.sql
sqlite3 /dev/shm/accu4_db_ram.sqlite < /tmp/commands.sql
rm -rf /tmp/commands.sql
