#!/bin/sh
if [ -z "$1" ]; then
	echo "usage: $0 <recipe_no> <preset_amt> <arm_no>"
	exit
fi

echo ".timeout 10000" > /tmp/commands.sql
echo "update batch_setup set recipe_no=$1, entered_preset=$2 where arm_no=$3;" >> /tmp/commands.sql
echo ".quit" >> /tmp/commands.sql
sqlite3 /dev/shm/accu4_db_ram.sqlite < /tmp/commands.sql
rm -rf /tmp/commands.sql
