#!/bin/sh

echo ".timeout 10000" > /tmp/commands.sql
echo ".headers ON" >> /tmp/commands.sql
echo "update comm_config set ip_addr='192.168.181.218';" >> /tmp/commands.sql
echo "update system_config set remote_browser=1;" >> /tmp/commands.sql
echo "update system_config set flow_simulator=1;" >> /tmp/commands.sql
echo ".quit" >> /tmp/commands.sql
sqlite3 /media/data/database/accu4_db.sqlite < /tmp/commands.sql
rm -rf /tmp/commands.sql
