#!/bin/sh

/usr/bin/create-json-pipe.sh data a4m > /dev/null
/usr/bin/create-json-pipe.sh data a4b > /dev/null
/usr/bin/create-json-pipe.sh mtr_inj a4m > /dev/null
/usr/bin/create-json-pipe.sh mtr_inj a4b > /dev/null
/usr/bin/create-json-pipe.sh mtr_inj a4i1 > /dev/null
/usr/bin/create-json-pipe.sh mtr_inj a4i2 > /dev/null
