#!/bin/sh

echo ".timeout 10000" > /tmp/commands.sql
echo ".mode column" >> /tmp/commands.sql
echo ".headers ON" >> /tmp/commands.sql
echo "select bay_no, arm_no, trans_no, tran_iv, tran_gv, tran_gst, tran_gsv, tran_mass from trans_arm_data where arm_no=2;" >> /tmp/commands.sql
echo ".quit" >> /tmp/commands.sql
sqlite3 /media/data/database/accu4_datalog.sqlite < /tmp/commands.sql
rm -rf /tmp/commands.sql
