alias grepc='grep -ihHnr --include=\*.{c,cpp,h}'
alias grepp='grep -ihHnr --include=\*.{py}'
alias aliv='cd /c/Users/allenma/Documents/projects/acculoadiv'
alias ml='cd /c/Users/allenma/Documents/projects/legacyproducts.microloadnet/source'
alias mfl='cd /c/Users/allenma/Documents/projects/legacyproducts.microflownet-liquid/source'
alias mfg='cd /c/Users/allenma/Documents/projects/legacyproducts.microflownet-gas/source'
alias al3='cd /c/Users/allenma/Documents/projects/legacyproducts.al3xnet/source'
alias scripts='cd /c/Users/allenma/Documents/projects/Internal-Software-Tools.automated_testing'
alias LOCAL='cd /c/Users/allenma/AppData/Local/TechnipFMC/Accumate\ for\ AccuLoad\ III.net'
alias AL3REM='./al3remotedisplay.exe COM0 ADDRC0A84C01 QUAD &'
alias github='cd /c/Users/allenma/Documents/Scripts_BASH_Repo'
alias gui='sudo cp /etc/default/grub.gui /etc/default/grub && sudo update-grub && reboot'
alias console='sudo cp /etc/default/grub.term /etc/default/grub && sudo update-grub && reboot'
alias transfer='cd ~/transfer'
alias zenva='cd /c/Users/allenma/Documents/zenva'
alias sketch=' cd /c/Users/allenma/Documents/arduino-1.8.13/portable/sketchbook'
alias lsr='ls -R'
alias craftos='cd /c/Users/allenma/AppData/Roaming/CraftOS-PC'
