# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S:\Electronics\Public\riverab2\AccuComm\AccuComm.ui'
#
# Created: Thu Aug 25 15:21:09 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.length_combo = QtGui.QComboBox(self.frame)
        self.length_combo.setObjectName("length_combo")
        self.gridLayout_4.addWidget(self.length_combo, 2, 1, 1, 1)
        self.stop_combo = QtGui.QComboBox(self.frame)
        self.stop_combo.setObjectName("stop_combo")
        self.gridLayout_4.addWidget(self.stop_combo, 2, 2, 1, 1)
        self.parity_combo = QtGui.QComboBox(self.frame)
        self.parity_combo.setObjectName("parity_combo")
        self.gridLayout_4.addWidget(self.parity_combo, 2, 0, 1, 1)
        self.baud_combo = QtGui.QComboBox(self.frame)
        self.baud_combo.setObjectName("baud_combo")
        self.gridLayout_4.addWidget(self.baud_combo, 0, 2, 1, 1)
	self.unlock_tiva_button = QtGui.QPushButton(self.frame)
        self.unlock_tiva_button.setObjectName("unlock_tiva_button")
        self.gridLayout_4.addWidget(self.unlock_tiva_button)
        self.com_combo = QtGui.QComboBox(self.frame)
        self.com_combo.setObjectName("com_combo")
        self.gridLayout_4.addWidget(self.com_combo, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(self.tab)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.protocol_combo = QtGui.QComboBox(self.frame_3)
        self.protocol_combo.setObjectName("protocol_combo")
        self.gridLayout_3.addWidget(self.protocol_combo, 0, 0, 1, 4)
        self.command_line = QtGui.QLineEdit(self.frame_3)
        self.command_line.setObjectName("command_line")
        self.gridLayout_3.addWidget(self.command_line, 4, 0, 1, 3)
        self.send_button = QtGui.QPushButton(self.frame_3)
        self.send_button.setObjectName("send_button")
        self.gridLayout_3.addWidget(self.send_button, 4, 3, 1, 1)
        self.start_button = QtGui.QPushButton(self.frame_3)
        self.start_button.setObjectName("start_button")
        self.gridLayout_3.addWidget(self.start_button, 2, 0, 1, 1)
	self.macro_checkbox = QtGui.QCheckBox(self.frame_3)
	self.macro_checkbox.setObjectName("macro_checkbox")
 	self.gridLayout_3.addWidget(self.macro_checkbox, 2, 3, 1, 1)
        self.connect_button = QtGui.QPushButton(self.frame_3)
        self.connect_button.setObjectName("connect_button")
        self.gridLayout_3.addWidget(self.connect_button, 2, 2, 1, 1)
        self.stop_button = QtGui.QPushButton(self.frame_3)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout_3.addWidget(self.stop_button, 2, 1, 1, 1)
        self.test_combo = QtGui.QComboBox(self.frame_3)
        self.test_combo.setObjectName("test_combo")
        self.gridLayout_3.addWidget(self.test_combo, 3, 0, 1, 4)
        self.gridLayout_5.addWidget(self.frame_3, 2, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.ip_line = QtGui.QLineEdit(self.frame_2)
        self.ip_line.setObjectName("ip_line")
        self.horizontalLayout.addWidget(self.ip_line)
        self.gridLayout_5.addWidget(self.frame_2, 1, 0, 1, 1)
        self.testPreview_edit = QtGui.QTextEdit(self.tab)
        self.testPreview_edit.setReadOnly(True)
        self.testPreview_edit.setObjectName("testPreview_edit")
        self.gridLayout_5.addWidget(self.testPreview_edit, 3, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 1, 0, 1, 4)
        self.addTab_button = QtGui.QPushButton(self.tab)
        self.addTab_button.setObjectName("addTab_button")
        self.gridLayout_6.addWidget(self.addTab_button, 0, 2, 1, 1)
        self.removeTab_button = QtGui.QPushButton(self.tab)
        self.removeTab_button.setObjectName("removeTab_button")
        self.gridLayout_6.addWidget(self.removeTab_button, 0, 3, 1, 1)
        self.serial_radio = QtGui.QRadioButton(self.tab)
        self.serial_radio.setObjectName("serial_radio")
        self.gridLayout_6.addWidget(self.serial_radio, 0, 1, 1, 1)
        self.tcp_radio = QtGui.QRadioButton(self.tab)
        self.tcp_radio.setChecked(True)
        self.tcp_radio.setObjectName("tcp_radio")
        self.gridLayout_6.addWidget(self.tcp_radio, 0, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_5 = QtGui.QFrame(self.tab)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.receiveHex_edit = QtGui.QTextEdit(self.frame_5)
        self.receiveHex_edit.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.receiveHex_edit.setReadOnly(True)
        self.receiveHex_edit.setObjectName("receiveHex_edit")
        self.gridLayout_8.addWidget(self.receiveHex_edit, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_5, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 2, 0, 1, 1)
        self.receive_edit = QtGui.QTextEdit(self.tab)
        self.receive_edit.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.receive_edit.setReadOnly(True)
        self.receive_edit.setObjectName("receive_edit")
        self.gridLayout_7.addWidget(self.receive_edit, 3, 0, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.transmit_edit = QtGui.QTextEdit(self.tab)
        self.transmit_edit.setReadOnly(True)
        self.transmit_edit.setObjectName("transmit_edit")
        self.gridLayout_7.addWidget(self.transmit_edit, 1, 0, 1, 1)
        self.frame_4 = QtGui.QFrame(self.tab)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.transmitHex_edit = QtGui.QTextEdit(self.frame_4)
        self.transmitHex_edit.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.transmitHex_edit.setReadOnly(True)
        self.transmitHex_edit.setObjectName("transmitHex_edit")
        self.gridLayout_9.addWidget(self.transmitHex_edit, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_4, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 0, 4, 2, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHex_View = QtGui.QAction(MainWindow)
        self.actionHex_View.setObjectName("actionHex_View")
        self.actionASCII_View = QtGui.QAction(MainWindow)
        self.actionASCII_View.setObjectName("actionASCII_View")
        self.actionHybrid_View = QtGui.QAction(MainWindow)
        self.actionHybrid_View.setObjectName("actionHybrid_View")
        self.actionCombined_View = QtGui.QAction(MainWindow)
        self.actionCombined_View.setObjectName("actionCombined_View")
        self.actionNo_View = QtGui.QAction(MainWindow)
        self.actionNo_View.setObjectName("actionNo_View")
        self.actionClear_All = QtGui.QAction(MainWindow)
        self.actionClear_All.setObjectName("actionClear_All")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuView.addAction(self.actionHex_View)
        self.menuView.addAction(self.actionASCII_View)
        self.menuView.addAction(self.actionHybrid_View)
        self.menuView.addAction(self.actionCombined_View)
        self.menuView.addAction(self.actionNo_View)
        self.menuView.addAction(self.actionClear_All)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.send_button.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.start_button.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.connect_button.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_button.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.unlock_tiva_button.setText(QtGui.QApplication.translate("MainWindow", "Unlock Tiva", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.addTab_button.setText(QtGui.QApplication.translate("MainWindow", "Add Session", None, QtGui.QApplication.UnicodeUTF8))
        self.removeTab_button.setText(QtGui.QApplication.translate("MainWindow", "Remove Session", None, QtGui.QApplication.UnicodeUTF8))
        self.serial_radio.setText(QtGui.QApplication.translate("MainWindow", "Serial", None, QtGui.QApplication.UnicodeUTF8))
        self.tcp_radio.setText(QtGui.QApplication.translate("MainWindow", "TCP", None, QtGui.QApplication.UnicodeUTF8))
        self.macro_checkbox.setText(QtGui.QApplication.translate("MainWindow", "Macro", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Receive", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Transmit", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Contents", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHex_View.setText(QtGui.QApplication.translate("MainWindow", "Hex View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionASCII_View.setText(QtGui.QApplication.translate("MainWindow", "ASCII View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHybrid_View.setText(QtGui.QApplication.translate("MainWindow", "Hybrid View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCombined_View.setText(QtGui.QApplication.translate("MainWindow", "Combined View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNo_View.setText(QtGui.QApplication.translate("MainWindow", "No View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_All.setText(QtGui.QApplication.translate("MainWindow", "Clear All", None, QtGui.QApplication.UnicodeUTF8))

