ErrCode	ErrMsg
0x0000	No error
0x0001	Download successful
0x8000	Empty config
0x8001	Block not found
0x8002	Bad message format
0x8003	Block out of sequence
0x8004	Invalid flash data
0x8005	Target buffer too small
0x8006	Bad CRC
0x8007	No config avail
0x8008	Download already in progress
0x8009	Bad database spec
0x800a	In program mode
0x800b	Released
0x800c	Bad value
0x800d	Flow active
0x800e	No transactions ever done
0x800f	Operation not allowed
0x8010	Wrong control mode
0x8011	Transaction in progress
0x8012	Alarm active
0x8013	Storage full
0x8014	Operation out of sequence
0x8015	Power fail during transaction
0x8016	Authorized
0x8017	Program code not used
0x8018	Disp key in remote control
0x8019	Ticket not in printer
0x801a	No key data pending
0x801b	No transaction in progress
0x801c	Option not installed
0x801d	Start after stop delay
0x801e	Permissive delay active
0x801f	Print request pending
0x8020	No meter enabled
0x8021	Must be in program mode
0x8022	Ticket alarm during transaction
0x8023	Volume type not selected
0x8024	Exactly one rec must be enabled
0x8025	Batch limit reached
0x8026	Checking entries
0x8027	Prod rec add not assigned
0x8028	Must use mini protocol
0x8029	Buffer error
0x802a	Keypad locked
0x802b	Data recall error
0x802c	Internal error
0x802d	Transmit reply
0x802e	Unknown error
0x802f	Unused batch
0x8030	Packing Memory (wait, and try again)
0x8031	Data not available
0x8032	Card In Required
0x8033	Too Many Shared Additives
8x8034	Max Active Arms in Use
0x8035	Transaction Not Standby
0x8036	Swing Arm Out of Position
0x8037	No Current Batch on Arm
0xc000	Internal flash error
0xc001	Flash has overrun
0xc002	Internal buffer error
0xc003	Buffer allocation error
0xc004	Buffer overrun
0xc005	Flash erase error
0xc006	Flash write error
